const mongoose = require('mongoose');
const Parking = require('./models/parking');

// 🔥 REPLACE with your actual MongoDB connection string
mongoose.connect("mongodb+srv://admin:admin123@cluster.hao7ajf.mongodb.net/?appName=Cluster")
  .then(() => console.log("MongoDB connected for seeding"))
  .catch(err => { console.error(err); process.exit(1); });

const data = [
  {
    name: "Karol Bagh Metro Parking",
    area: "Karol Bagh",
    lat: 28.6519, lng: 77.1909,
    type: "Metro",
    price: 20,
    hours: "6 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 22, total: 30,
    rating: 4.2,
    features: ["CCTV", "Covered", "Washroom"],
  },
  {
    name: "Karol Bagh Central Market",
    area: "Karol Bagh",
    lat: 28.6505, lng: 77.1926,
    type: "Market",
    price: 25,
    hours: "8 AM – 10 PM",
    vehicles: ["car", "bike"],
    avail: 10, total: 15,
    rating: 4.0,
    features: ["Open", "Security"],
  },
  {
    name: "Connaught Place Parking P-2",
    area: "Connaught Place",
    lat: 28.6315, lng: 77.2167,
    type: "Mall/CP",
    price: 40,
    hours: "24/7",
    vehicles: ["car", "bike", "truck"],
    avail: 5, total: 60,
    rating: 4.5,
    features: ["Covered", "Valet", "EV Charging"],
  },
  {
    name: "Rajiv Chowk Metro Basement",
    area: "Connaught Place",
    lat: 28.6328, lng: 77.2197,
    type: "Metro",
    price: 30,
    hours: "6 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 18, total: 40,
    rating: 4.3,
    features: ["Covered", "CCTV"],
  },
  {
    name: "Lajpat Nagar Metro Parking",
    area: "Lajpat Nagar",
    lat: 28.5672, lng: 77.2436,
    type: "Metro",
    price: 20,
    hours: "6 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 14, total: 25,
    rating: 4.1,
    features: ["CCTV", "Open"],
  },
  {
    name: "Lajpat Nagar Central Market",
    area: "Lajpat Nagar",
    lat: 28.5659, lng: 77.2436,
    type: "Market",
    price: 25,
    hours: "9 AM – 9 PM",
    vehicles: ["car", "bike"],
    avail: 7, total: 20,
    rating: 3.9,
    features: ["Open", "Security"],
  },
  {
    name: "Select CityWalk Saket",
    area: "Saket",
    lat: 28.5274, lng: 77.2190,
    type: "Mall",
    price: 50,
    hours: "10 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 35, total: 500,
    rating: 4.6,
    features: ["Covered", "Valet", "EV Charging", "Washroom"],
  },
  {
    name: "Saket Metro Parking",
    area: "Saket",
    lat: 28.5224, lng: 77.2057,
    type: "Metro",
    price: 20,
    hours: "6 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 12, total: 30,
    rating: 4.0,
    features: ["CCTV", "Open"],
  },
  {
    name: "Nehru Place Multi-level",
    area: "Nehru Place",
    lat: 28.5491, lng: 77.2509,
    type: "Multi-level",
    price: 35,
    hours: "8 AM – 10 PM",
    vehicles: ["car", "bike", "truck"],
    avail: 3, total: 50,
    rating: 4.4,
    features: ["Covered", "Security", "Washroom"],
  },
  {
    name: "DLF Promenade Vasant Kunj",
    area: "Vasant Kunj",
    lat: 28.5178, lng: 77.1590,
    type: "Mall",
    price: 45,
    hours: "10 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 28, total: 300,
    rating: 4.5,
    features: ["Covered", "EV Charging", "Valet"],
  },
  {
    name: "Hauz Khas Metro Parking",
    area: "Hauz Khas",
    lat: 28.5437, lng: 77.2066,
    type: "Metro",
    price: 20,
    hours: "6 AM – 11 PM",
    vehicles: ["car", "bike"],
    avail: 9, total: 20,
    rating: 4.0,
    features: ["Open", "CCTV"],
  },
  {
    name: "Khan Market Parking",
    area: "Khan Market",
    lat: 28.6004, lng: 77.2266,
    type: "Market",
    price: 40,
    hours: "9 AM – 10 PM",
    vehicles: ["car"],
    avail: 4, total: 12,
    rating: 4.2,
    features: ["Open", "Security"],
  },
  {
  name: "V3S Mall Laxmi Nagar Parking",
  area: "Laxmi Nagar",
  lat: 28.6304, lng: 77.2773,
  type: "Mall",
  price: 30,
  hours: "10 AM – 10 PM",
  vehicles: ["car", "bike"],
  avail: 25, total: 150,
  rating: 4.1,
  features: ["Covered", "Security", "Washroom"],
},
{
  name: "Preet Vihar Metro Parking",
  area: "Preet Vihar",
  lat: 28.6374, lng: 77.2955,
  type: "Metro",
  price: 20,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 18, total: 40,
  rating: 4.0,
  features: ["CCTV", "Open"],
},
{
  name: "South Extension Market Parking",
  area: "South Extension",
  lat: 28.5681, lng: 77.2205,
  type: "Market",
  price: 40,
  hours: "10 AM – 9 PM",
  vehicles: ["car", "bike"],
  avail: 6, total: 20,
  rating: 4.2,
  features: ["Security", "Open"],
},
{
  name: "Greater Kailash M Block Parking",
  area: "Greater Kailash",
  lat: 28.5494, lng: 77.2350,
  type: "Market",
  price: 50,
  hours: "10 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 10, total: 35,
  rating: 4.5,
  features: ["Valet", "Security"],
},
{
  name: "Okhla Phase 1 Parking Hub",
  area: "Okhla",
  lat: 28.5355, lng: 77.2711,
  type: "Commercial",
  price: 25,
  hours: "8 AM – 8 PM",
  vehicles: ["car", "bike", "truck"],
  avail: 30, total: 80,
  rating: 4.0,
  features: ["Open", "Large Space"],
},
{
  name: "Nehru Stadium Parking",
  area: "Lodhi Road",
  lat: 28.5823, lng: 77.2336,
  type: "Event",
  price: 35,
  hours: "6 AM – 10 PM",
  vehicles: ["car", "bike", "bus"],
  avail: 40, total: 200,
  rating: 4.3,
  features: ["Security", "Large Space"],
},
{
  name: "Delhi Haat INA Parking",
  area: "INA",
  lat: 28.5733, lng: 77.2098,
  type: "Tourist",
  price: 30,
  hours: "10 AM – 10 PM",
  vehicles: ["car", "bike"],
  avail: 12, total: 60,
  rating: 4.4,
  features: ["Open", "Security", "Washroom"],
},
{
  name: "ITO Parking Complex",
  area: "ITO",
  lat: 28.6289, lng: 77.2410,
  type: "Commercial",
  price: 25,
  hours: "8 AM – 8 PM",
  vehicles: ["car", "bike"],
  avail: 14, total: 50,
  rating: 4.0,
  features: ["Covered", "CCTV"],
},
{
  name: "Pragati Maidan Parking",
  area: "Pragati Maidan",
  lat: 28.6139, lng: 77.2425,
  type: "Exhibition",
  price: 40,
  hours: "9 AM – 7 PM",
  vehicles: ["car", "bike", "bus"],
  avail: 60, total: 300,
  rating: 4.5,
  features: ["Large Space", "Security"],
},
{
  name: "Shivaji Stadium Parking",
  area: "Connaught Place",
  lat: 28.6322, lng: 77.2131,
  type: "Metro",
  price: 30,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 11, total: 45,
  rating: 4.1,
  features: ["Covered", "CCTV"],
},
{
  name: "Rohini Sector 18 Parking",
  area: "Rohini",
  lat: 28.7343, lng: 77.1220,
  type: "Residential",
  price: 15,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 22, total: 60,
  rating: 3.9,
  features: ["Open", "Security"],
},
{
  name: "Pitampura TV Tower Parking",
  area: "Pitampura",
  lat: 28.7026, lng: 77.1426,
  type: "Public",
  price: 20,
  hours: "6 AM – 10 PM",
  vehicles: ["car", "bike"],
  avail: 16, total: 50,
  rating: 4.0,
  features: ["Open", "CCTV"],
},
{
  name: "Netaji Subhash Place Parking",
  area: "NSP",
  lat: 28.6957, lng: 77.1522,
  type: "Commercial",
  price: 35,
  hours: "10 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 20, total: 120,
  rating: 4.3,
  features: ["Covered", "Valet"],
},
{
  name: "Yamuna Sports Complex Parking",
  area: "Surajmal Vihar",
  lat: 28.6605, lng: 77.3050,
  type: "Sports",
  price: 25,
  hours: "6 AM – 9 PM",
  vehicles: ["car", "bike"],
  avail: 35, total: 100,
  rating: 4.4,
  features: ["Large Space", "Security"],
},
{
  name: "Mayur Vihar Phase 1 Parking",
  area: "Mayur Vihar",
  lat: 28.6062, lng: 77.2963,
  type: "Residential",
  price: 15,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 18, total: 70,
  rating: 3.8,
  features: ["Open", "Security"],
},
{
  name: "Ambience Mall Vasant Kunj Parking",
  area: "Vasant Kunj",
  lat: 28.5245, lng: 77.1547,
  type: "Mall",
  price: 50,
  hours: "10 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 60, total: 400,
  rating: 4.6,
  features: ["Covered", "Valet", "EV Charging"],
},
{
  name: "Qutub Minar Parking Area",
  area: "Mehrauli",
  lat: 28.5244, lng: 77.1855,
  type: "Tourist",
  price: 30,
  hours: "7 AM – 6 PM",
  vehicles: ["car", "bike"],
  avail: 20, total: 80,
  rating: 4.5,
  features: ["Security", "Open"],
},
{
  name: "AIIMS Metro Parking",
  area: "AIIMS",
  lat: 28.5672, lng: 77.2100,
  type: "Metro",
  price: 20,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 12, total: 35,
  rating: 4.2,
  features: ["CCTV", "Covered"],
},
{
  name: "Safdarjung Hospital Parking",
  area: "Safdarjung",
  lat: 28.5670, lng: 77.2070,
  type: "Hospital",
  price: 25,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 8, total: 50,
  rating: 4.0,
  features: ["Security", "Open"],
},
{
  name: "Delhi Cantt Railway Station Parking",
  area: "Delhi Cantt",
  lat: 28.5880, lng: 77.1333,
  type: "Railway",
  price: 20,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 15, total: 60,
  rating: 4.1,
  features: ["CCTV", "Open"],
},
{
  name: "New Delhi Railway Station Parking",
  area: "Paharganj",
  lat: 28.6427, lng: 77.2197,
  type: "Railway",
  price: 40,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 5, total: 100,
  rating: 4.3,
  features: ["Covered", "Security"],
},
{
  name: "Rajiv Gandhi Sports Complex Parking",
  area: "Rohini",
  lat: 28.7150, lng: 77.1150,
  type: "Sports",
  price: 25,
  hours: "6 AM – 9 PM",
  vehicles: ["car", "bike"],
  avail: 30, total: 120,
  rating: 4.4,
  features: ["Large Space", "Security"],
},
{
  name: "Ashok Vihar Phase 1 Parking",
  area: "Ashok Vihar",
  lat: 28.6920, lng: 77.1710,
  type: "Residential",
  price: 15,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 20, total: 70,
  rating: 3.9,
  features: ["Open", "Security"],
},
{
  name: "Civil Lines Metro Parking",
  area: "Civil Lines",
  lat: 28.6765, lng: 77.2240,
  type: "Metro",
  price: 20,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 14, total: 40,
  rating: 4.1,
  features: ["CCTV", "Covered"],
},
{
  name: "Majnu Ka Tila Parking",
  area: "Majnu Ka Tila",
  lat: 28.6990, lng: 77.2275,
  type: "Market",
  price: 30,
  hours: "10 AM – 10 PM",
  vehicles: ["car", "bike"],
  avail: 9, total: 35,
  rating: 4.2,
  features: ["Open", "Security"],
},
{
  name: "Burari Ground Parking",
  area: "Burari",
  lat: 28.7525, lng: 77.1990,
  type: "Public",
  price: 10,
  hours: "24/7",
  vehicles: ["car", "bike"],
  avail: 40, total: 150,
  rating: 3.8,
  features: ["Large Space"],
},
{
  name: "Kirti Nagar Metro Parking",
  area: "Kirti Nagar",
  lat: 28.6550, lng: 77.1500,
  type: "Metro",
  price: 20,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 17, total: 45,
  rating: 4.0,
  features: ["CCTV", "Open"],
},
{
  name: "Naraina Industrial Area Parking",
  area: "Naraina",
  lat: 28.6290, lng: 77.1350,
  type: "Industrial",
  price: 25,
  hours: "8 AM – 8 PM",
  vehicles: ["car", "truck"],
  avail: 22, total: 90,
  rating: 4.1,
  features: ["Large Space", "Security"],
},
{
  name: "Shahdara Metro Parking",
  area: "Shahdara",
  lat: 28.6735, lng: 77.2875,
  type: "Metro",
  price: 20,
  hours: "6 AM – 11 PM",
  vehicles: ["car", "bike"],
  avail: 13, total: 50,
  rating: 4.0,
  features: ["CCTV", "Open"],
},
{
  name: "Seelampur Market Parking",
  area: "Seelampur",
  lat: 28.6695, lng: 77.2680,
  type: "Market",
  price: 25,
  hours: "9 AM – 9 PM",
  vehicles: ["car", "bike"],
  avail: 7, total: 30,
  rating: 3.9,
  features: ["Open", "Security"],
},
];

async function seed() {
  await Parking.deleteMany({});
  await Parking.insertMany(data);
  console.log(`✓ Inserted ${data.length} parking spots`);
  process.exit();
}

seed();